 #멤버 정보 테이블
 CREATE TABLE SHOP_MEMBER (
 	MEM_ID VARCHAR(20) PRIMARY KEY #ID
 	, MEM_PW VARCHAR(20) NOT NULL #비번
 	, MEM_NAME VARCHAR(20) NOT NULL #이름
 	, MEM_TEL_ARR VARCHAR(15) #전화번호(배열)
 	, MEM_EMAIL VARCHAR(30) NOT NULL #이메일
 	, MEM_ADDR VARCHAR (20) NOT NULL #주소
 	, ADDR_DETAIL VARCHAR(20) #상세주소
 );
 
 #상품정보
 CREATE TABLE ITEM (
 	ITEM_NUM INT PRIMARY KEY #상품 번호
 	, ITEM_NAME VARCHAR(20) NOT NULL UNIQUE #상품명
 	, PRICE INT NOT NULL #가격
 	, ITEM_INTRO VARCHAR(500) #상품 소개
 	, PART VARCHAR(10) #부위
 	, REG_DATE DATETIME DEFAULT SYSDATE() #상품 등록일
 );
 
 DROP TABLE item;
 
 #상품 이미지 테이블
 CREATE TABLE ITEM_IMG (
 	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ORIGIN_IMG_NAME VARCHAR(100) #원본 파일명
	, ATTACHED_IMG_NAME VARCHAR(100) #첨부된 파일명
	, ITEM_NUM INT REFERENCES ITEM (ITEM_NUM) ON DELETE CASCADE #이미지의 원본 도서 번호
	, IS_MAIN VARCHAR(3) #메인이미지 : 'Y', 서브이미지 : 'N'
 );
 
 #평점 테이블
 CREATE TABLE REVIEW (
 	REVIEW_NUM INT PRIMARY KEY AUTO_INCREMENT #평점 번호
 	, RATING INT NOT NULL #별점
 	, TITLE VARCHAR(30) NOT NULL #제목
 	, MEM_ID VARCHAR(20) NOT NULL REFERENCES SHOP_MEMBER(MEM_ID) #회원 ID
 	, ITEM_NUM INT NOT NULL REFERENCES ITEM(ITEM_NUM) #상품 번호
 	, CONTENT VARCHAR(1000) NOT NULL #내용
 	, READ_CNT INT
 	, CREATE_DATE DATETIME DEFAULT SYSDATE() #등록일
 );
  
 #평점 이미지 등록 테이블
 CREATE TABLE REVIEW_IMG (
 	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ORIGIN_IMG_NAME VARCHAR(100) #원본 파일명
	, ATTACHED_IMG_NAME VARCHAR(100) #첨부된 파일명
	, REVIEW_NUM INT REFERENCES REVIEW (REVIEW_NUM) ON DELETE CASCADE #이미지의 원본 도서 번호
 );
 
 
 
 
 #################################################
 ### 이 워크시트에 CREATE 문을 다 작성해주세요 ###