 #멤버 정보 테이블
 CREATE TABLE SHOP_MEMBER (
 	MEM_ID VARCHAR(20) PRIMARY KEY
 	, MEM_PW VARCHAR(20) NOT NULL
 	, MEM_NAME VARCHAR(20) NOT NULL
 	, MEM_TEL_ARR VARCHAR(15)
 	, MEM_EMAIL VARCHAR(30) NOT NULL
 	, MEM_ADDR VARCHAR (20) NOT NULL
 	, ADDR_DETAIL VARCHAR(20)
 );
 
 #평점 테이블
 CREATE TABLE REVIEW (
 	REVIEW_NUM INT PRIMARY KEY AUTO_INCREMENT
 	, RAITING INT NOT NULL
 	, TITLE VARCHAR(30) NOT NULL
 	, MEM_ID VARCHAR(20) NOT NULL REFERENCES SHOP_MEMBER(MEM_ID)
 	, ITEM_NUM INT NOT NULL REFERENCES ITEM(ITEM_NUM)
 	, CONTENT VARCHAR(1000) NOT NULL
 	, CREATE_DATE DATETIME DEFAULT SYSDATE()
 );
 
 #평점 이미지 등록 테이블
 CREATE TABLE REVIEW_IMG (
 	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ORIGIN_IMG_NAME VARCHAR(100) #원본 파일명
	, ATTACHED_IMG_NAME VARCHAR(100) #첨부된 파일명
	, REVIEW_NUM INT REFERENCES REVIEW (BOOK_NUM) ON DELETE CASCADE #이미지의 원본 도서 번호
	, IS_MAIN VARCHAR(3) #메인이미지 : 'Y', 서브이미지 : 'N'
 );
 
 
 
 
 #################################################
 ### 이 워크시트에 CREATE 문을 다 작성해주세요 ###