#멤버 정보 테이블
 CREATE TABLE SHOP_MEMBER (
 	MEM_ID VARCHAR(20) PRIMARY KEY #ID
 	, MEM_PW VARCHAR(20) NOT NULL #비번
 	, MEM_NAME VARCHAR(20) NOT NULL #이름
 	, MEM_TEL VARCHAR(15) #전화번호(배열)
 	, MEM_EMAIL VARCHAR(30) NOT NULL #이메일
 	, MEM_ADDR VARCHAR (20) NOT NULL #주소
 	, ADDR_DETAIL VARCHAR(20) #상세주소
  , PW_KEY INT REFERENCES forgotpw(PW_KEY) #비밀번호 찾기 질문 번호
  , PW_ANSWER VARCHAR(20) NOT NULL #비밀번호 찾기 질문 답변    
  , MEM_ROLE VARCHAR(14) NOT NULL DEFAULT 'USER'     #관리자는 ADMIN
  , JOIN_DATE DATETIME DEFAULT SYSDATE()
  ); 
 
 #상품정보
 CREATE TABLE ITEM (
 	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT #상품 번호
 	, ITEM_NAME VARCHAR(20) NOT NULL UNIQUE #상품명
 	, PRICE INT NOT NULL #가격
 	, ITEM_INTRO VARCHAR(500) #상품 소개
 	, PART VARCHAR(10) #부위
 	, REVIEW_AVG DOUBLE DEFAULT 0 #평균 평점
 	, ORIGIN VARCHAR(15) #원산지
 	, REG_DATE DATETIME DEFAULT SYSDATE() #상품 등록일
 );
 
 #상품 이미지 테이블
 CREATE TABLE ITEM_IMG (
 	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ORIGIN_IMG_NAME VARCHAR(100) #원본 파일명
	, ATTACHED_IMG_NAME VARCHAR(100) #첨부된 파일명
	, ITEM_NUM INT REFERENCES ITEM (ITEM_NUM) ON DELETE CASCADE #상품 번호
	, IS_MAIN VARCHAR(3) #메인이미지 : 'Y', 서브이미지 : 'N'
 );
 
 #평점 테이블
 CREATE TABLE REVIEW (
 	REVIEW_NUM INT PRIMARY KEY AUTO_INCREMENT #평점 번호
 	, RATING INT NOT NULL #별점
 	, TITLE VARCHAR(30) NOT NULL #제목
 	, MEM_ID VARCHAR(20) NOT NULL REFERENCES SHOP_MEMBER(MEM_ID) #회원 ID
 	, ITEM_NUM INT NOT NULL REFERENCES ITEM(ITEM_NUM) #상품 번호
 	, CONTENT VARCHAR(1000) NOT NULL #내용
 	, READ_CNT INT DEFAULT 0  #조회수
 	, CREATE_DATE DATETIME DEFAULT SYSDATE() #등록일
 ); 
  
 #평점 이미지 등록 테이블
 CREATE TABLE REVIEW_IMG (
 	REVIEW_IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, REVIEW_ORIGIN_IMG_NAME VARCHAR(100) #원본 파일명
	, REVIEW_ATTACHED_IMG_NAME VARCHAR(100) #첨부된 파일명
	, REVIEW_NUM INT REFERENCES REVIEW (REVIEW_NUM) ON DELETE CASCADE #리뷰 번호
 );  
 
 #라즈베리파이 관리자 기능(온,습도 센서를 이용한 fan 액츄에이터 구현)
 CREATE TABLE FAN_FUNCTION (
 	THV_ID INT PRIMARY KEY AUTO_INCREMENT
 	, TEMPERATURE FLOAT  	
 	, HUMIDITY FLOAT 
 	, AIR_QUALITY INT 
 	, CREATE_DATE DATETIME DEFAULT SYSDATE()
 ); 
 
  #라즈베리파이 관리자 기능(조도센서를 이용한 LED 액츄에이터 구현)
 CREATE TABLE illuminance_function(
 	IM_ID INT PRIMARY KEY AUTO_INCREMENT
 	, ILLUMINANCE INT
 	, CREATE_DATE DATETIME DEFAULT SYSDATE()
 ); 
 
 #비밀번호 찾기용 질문 테이블
 CREATE TABLE forgotpw (
 PW_KEY INT PRIMARY KEY AUTO_INCREMENT #질문 번호
 , PW_QUESTION VARCHAR(50) NOT NULL #질문 내용 
 );  
 
 #장바구니 테이블 
 CREATE TABLE SHOP_CART(
  CART_NUM INT PRIMARY KEY AUTO_INCREMENT
  , ITEM_NUM INT REFERENCES ITEM(ITEM_NUM)
  , CART_CNT INT NOT NULL
  , MEM_ID VARCHAR(20) REFERENCES SHOP_MEMBER(MEM_ID)
  , TOTAL_PRICE INT NOT NULL
  , CART_DATE DATETIME DEFAULT SYSDATE()
 );
 
 #구매 테이블
 CREATE TABLE SHOP_BUY(
  BUY_NUM INT PRIMARY KEY AUTO_INCREMENT
  , ITEM_NUM INT REFERENCES ITEM(ITEM_NUM)
  , MEM_ID VARCHAR(20) REFERENCES SHOP_MEMBER(MEM_ID)
  , BUY_DATE DATETIME DEFAULT SYSDATE()
  , BUY_CNT INT #구매수량
  , ORDER_NUM INT #주문번호, 한 번에 여러 상품을 구매하면 동일한 주문번호를 가진다
 );
 
 #Q&A 테이블
 CREATE TABLE qna(
 	QNA_NUM INT PRIMARY KEY AUTO_INCREMENT
 	,	ITEM_NUM INT REFERENCES ITEM(ITEM_NUM)
 	,	MEM_ID VARCHAR(20) REFERENCES SHOP_MEMBER(MEM_ID)
 	,	QNA_DATE DATETIME DEFAULT SYSDATE()
 	,	CONTENT VARCHAR(300)
 ); 
 
 #################################################
 ### 이 워크시트에 CREATE 문을 다 작성해주세요 ###
 